### PR TITLE
NOJIRA Do not store months as minutes in H2

### PR DESCRIPTION
**Pull request by raydavis**
Cheers, all. Hope you don't mind a surprise PR -- seemed simpler than opening a SISRP JIRA....

I was working on some test code in RTL Junction and couldn't figure out why every date was showing up as January. Turned out it was because our two-digit month specifications were actually being parsed as minutes because H2 uses SimpleDateFormat: https://docs.oracle.com/javase/10/docs/api/java/text/SimpleDateFormat.html

### CODE REVIEW

**Comment by redconfetti** [comment]
```
Failures:
  1) Berkeley::Terms Hub Term API feature flag disabled uses only the legacy DB, even for non-legacy semesters
     Failure/Error: expect(subject.future).to be_nil
     
       expected: nil
            got: #<Berkeley::Term>
     # ./spec/models/berkeley/terms_spec.rb:354:in `block in (root)'
Finished in 2 minutes 41.2 seconds (files took 23.41 seconds to load)
3464 examples, 1 failure
Failed examples:
rspec ./spec/models/berkeley/terms_spec.rb:351 # Berkeley::Terms Hub Term API feature flag disabled uses only the legacy DB, even for non-legacy semesters
```

**Comment by raydavis** [comment]
I didn't notice that on our own code, @redconfetti , because we removed that test: it's for a CS-transitional condition which interests you and us no longer, and is no longer viable even for test code. The reason it's been quietly passing all this time is this exact bug:

1. If you check your H2 loading files, you'll see that the Fall 2016 term is defined both in `populate_campus_h2.rb` _and_ `populate_sisedo_h2.rb`.

2. First, load_terms_from_edo_db is called. Given the fake-SISEDO data, this consists only of Fall 2016.

3. Because test code (unlike our production systems) is still allowed to fall back to the legacy "fake-ODS" DB and because the obsolete Berkeley::Terms.merge_terms_from_legacy_db method is still assuming that the legacy DB is going to be used instead of SISEDO, a Fall 2016 definition is loaded from fake-ODS and appended to the existing list.

3. The final working array begins with two separate Fall 2016 rows, one from fake-SISEDO and one from fake-ODS.

4. Because of the bug fixed by this PR, the fake-SISEDO Fall 2016 had a supposed `start` date of Jan. 17, 2016 (instead of the intended Aug. 17) and `end` date of Jan. 16. Unsurprisingly, the Berkeley::Terms parsing/sorting logic ended up skipping it.

5. As of this bug fix, the fake-SISEDO Fall 2016 row hangs right in there, and results in the fake-ODS Fall 2016 appearing after the fake-SISEDO one.

Personally, I'd recommend deleting the obsolete code. I can add that to this PR if you'd like.

**Comment by redconfetti** [comment]
@raydavis - Next time feel free to just let us know if it's failing for us but not you. You're not obligated to solve the cause of differences. We appreciate the PR regardless.

If you can remove the code this time, since you're familiar with the fix, please do. As far as I know, we're planning to rip out all support for legacy fallback once we have a chance. In fact it's my next task in [SISRP-45792](https://jira-secure.berkeley.edu/browse/SISRP-45792)

**Comment by raydavis** [comment]
Thanks, @redconfetti . At least it was an amusing problem to explain -- gotta love those bug interdependencies.

PR amended. Hopefully it's not too controversial.

**Comment by raydavis** [comment]
I guess you folks still have a lot of tests which have grown to rely on exclusion-of-SISEDO-terms-by-bug. I've run out of time for tinkering on this myself, so I'll close the PR. At least it managed to get word to you.

**Comment by redconfetti** [comment]
I've created [JIRA SISRP-48622](https://jira-secure.berkeley.edu/browse/SISRP-48622) for us to apply this fix later. Thanks @raydavis

**Pull request closed without merging**
